export const demoOptions = {
  categories: ['全部', '媒体', '学术', '公益', '文艺', '体育'],
  collegeOptions: [
    '计算机学院',
    '软件学院',
    '人工智能学院',
    '信息工程学院',
    '电子工程学院',
    '机械工程学院',
    '自动化学院',
    '土木工程学院',
    '经济管理学院',
    '法学院',
    '外国语学院',
    '新闻传播学院',
    '艺术学院',
    '教育学院',
    '医学院',
  ],
  gradeOptions: Array.from({ length: 5 }, (_, index) => `${new Date().getFullYear() - index}级`),
  interestOptions: ['媒体运营', '摄影摄像', '设计创意', '竞赛科研', '公益服务', '活动策划', '体育运动', '音乐舞蹈'],
  skillOptions: ['文案写作', '平面设计', '视频剪辑', '编程开发', '组织协调', '主持表达'],
  expectedGainOptions: ['技能提升', '社交拓展', '比赛经历', '志愿服务', '表达机会'],
} as const
